### PR TITLE
fix #99 Make Setter beans unnecessary and create a snapshot version.

### LINKED ISSUE #99: [1.1.1] org.springframework.beans.factory.NoSuchBeanDefinitionException
```log
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<org.nebula.contrib.ngbatis.binding.Setter<?>>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1799)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1355)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
	... 106 more
```

When this exception occurs in your project, please refer to the following steps:
Because the specific type of BigDecimal attribute in the project database cannot be determined, the project needs to be configured according to its own needs:
    1. Refer to [ValueType](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/annotations/ValueType.java) to create annotations that can distinguish entity attributes (or use existing annotations in your own project)
    2. Refer to [BigDecimalSetter](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/config/BigDecimalSetter.java) to configure different field types.
    3. [If BigDecimal is used] Place the annotation on the BigDecimal attribute of the java entity class, such as the height attribute in [Person](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/Person.java).

----
当项目中出现此异常时，请参考以下步骤：
因为不能确定BigDecimal的属性在项目数据库中所对应的具体类型，项目中需要根据自身需要进行配置：
    1. 参考[ ValueType ](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/annotations/ValueType.java) 创建能为实体属性做类型区分的注解（或使用自身项目中已有注解）
    2. 参考[ BigDecimalSetter ](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/config/BigDecimalSetter.java)对不同的字段类型配置。
    3. 【如果项目中使用了BigDecimal】将注解放置到java实体类的BigDecimal属性上，如[ Person ](https://github.com/nebula-contrib/ngbatis/blob/master/ngbatis-demo/src/main/java/ye/weicheng/ngbatis/demo/pojo/Person.java)中的 height 属性。

### PR DESCRIPTION
**Pull request by CorvusYe**

### CODE REVIEW

File: src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java [hunk 1]
```diff
@@ -260,6 +260,9 @@ public static boolean isMatchedErrorCode(ResultSet resultSet, ErrorCode... error
    * @return 是否命中session失效情况
    */
   public static boolean isSessionError(ResultSet resultSet) {
+    if (resultSet == null) {
+      return true;
+    }
```
Comment (CorvusYe) [inline src/main/java/org/nebula/contrib/ngbatis/utils/ResultSetUtil.java:265]: @soul-gin 
When executeWithParameter throw Exception sometimes cause by session error, 
and resultSet will be null at that moment.

File: src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java [hunk 2]
```diff
@@ -243,8 +241,18 @@ public static ResultSet executeWithParameter(ClassModel cm, MethodModel mm, Stri
...
+      handleSession(dispatcher, localSession, result);
+    }
+  }
+
+  private static void handleSession(SessionDispatcher dispatcher,
+      LocalSession localSession, ResultSet result) {
+    if (localSession != null) {
+      boolean sessionError = ResultSetUtil.isSessionError(result);
+      if (sessionError) {
+        dispatcher.release(localSession);
```
Comment (CorvusYe) [inline src/main/java/org/nebula/contrib/ngbatis/proxy/MapperProxy.java:253]: When session error, such as connection reset, release a session wound be a better practices.
Otherwise the dead session will still in line.

**Review by wey-gu — APPROVED** [review]
